name: CI Python Matrix

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test-matrix:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.9', '3.10', '3.11']

    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Instalar dependencias
      run: |
        cd mi-app-python
        pip install -r requirements.txt

    - name: Ejecutar tests
      run: |
        cd mi-app-python
        PYTHONPATH=$(pwd) pytest tests/ -v
