name: Deploy con Docker Compose

on:
  push:
    branches: [main, develop]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: [self-hosted, Linux, ARM64, jftp-runner]

    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Mostrar directorio raíz y contenido de la app
        run: |
          pwd
          ls -la
          ls -la mi-app

      - name: Docker Compose Down (limpiar contenedores)
        run: docker compose down -v || true
        working-directory: mi-app

      - name: Docker Compose Build (reconstruir imágenes)
        run: docker compose build
        working-directory: mi-app

      - name: Docker Compose Up (levantar servicios)
        run: docker compose up -d
        working-directory: mi-app

      - name: Verificar app con curl
        run: curl -f http://localhost:3000/health

      - name: Mostrar contenedores docker activos
        run: docker ps -a
      
      - name: Logs docker-compose
        run: docker compose logs
        working-directory: mi-app

